Move non-relevant code from Marine repo into FluenceJS
fluencelabs/marine pull request #235
Opened 2022-11-25 15:50 UTC by coder11

2022-12-01 14:45 UTC, shamsartem requested changes
Suggested a small improvement.
Will you move everything that you removed to the fluence-js repo right?

2022-12-01 14:45 UTC, shamsartem commented on marine-js/npm-package/src/__test__/logging.spec.ts
> +    return module;
"module" is sometimes a reserved keyword but also you can just do
```ts
return WebAssembly.compile(buffer)
```
it will behave absolutely identically

2022-12-01 14:45 UTC, shamsartem commented on marine-js/npm-package/tsconfig.json
> +, "src/.ts"    ],
I think there are some problems with formatting here

2022-12-02 10:23 UTC, coder11 commented
> Suggested a small improvement. Will you move everything that you removed to the fluence-js repo right?

Yeah, everything will go into the FlunceJS repo. I will make the PR once we finish with this

2022-12-05 10:50 UTC, mikevoronov approved these changes
utACK

2022-12-05 11:39 UTC, ValeryAntopol approved these changes
utACK

2022-12-05 19:29 UTC, shamsartem approved these changes
Thanks!

2022-12-06 06:50 UTC, merged